/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f0xx.h"

int main(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER5_0;
	GPIOA->BSRR = (1<<5); // set
	uint8_t pole[] =  {1,0,1,0,1,0,0,1,1,1,0,1,1,1,0,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0};

	for(;;){

		for (uint32_t i = 0; i < sizeof(pole); i++) {

			if (pole[i]==1){
				GPIOA->BSRR = (1<<5); // set

			}
			else {
				GPIOA->BRR = (1<<5); // reset

			}
			for (volatile uint32_t t = 0; t < 100000; t++) {}
		}

	}

	for (volatile uint32_t j = 0; j < 500000; j++) {}

}
